-- Session: Outbox for webhook triggers + pickup PIN verification RPC

-- 1) Edge webhook outbox (replaces in-transaction net.http_post)
CREATE TABLE IF NOT EXISTS public.edge_webhook_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  function_name text NOT NULL,
  secret_name text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending',
  attempts integer NOT NULL DEFAULT 0,
  next_attempt_at timestamptz NOT NULL DEFAULT now(),
  locked_at timestamptz,
  lock_id uuid,
  last_dispatched_at timestamptz,
  last_http_status integer,
  last_error text
);

-- Basic status validation
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'edge_webhook_outbox_status_check'
  ) THEN
    ALTER TABLE public.edge_webhook_outbox
      ADD CONSTRAINT edge_webhook_outbox_status_check
      CHECK (status IN ('pending','processing','sent','failed'));
  END IF;
END $$;

-- updated_at trigger (uses existing helper)
DROP TRIGGER IF EXISTS edge_webhook_outbox_set_updated_at ON public.edge_webhook_outbox;
CREATE TRIGGER edge_webhook_outbox_set_updated_at
BEFORE UPDATE ON public.edge_webhook_outbox
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX IF NOT EXISTS ix_edge_webhook_outbox_due
  ON public.edge_webhook_outbox (status, next_attempt_at, id);

CREATE INDEX IF NOT EXISTS ix_edge_webhook_outbox_lock
  ON public.edge_webhook_outbox (lock_id, locked_at);

-- Keep table private (service_role only)
REVOKE ALL ON TABLE public.edge_webhook_outbox FROM PUBLIC;
REVOKE ALL ON TABLE public.edge_webhook_outbox FROM anon;
REVOKE ALL ON TABLE public.edge_webhook_outbox FROM authenticated;
GRANT ALL ON TABLE public.edge_webhook_outbox TO service_role;

-- 2) Rewrite _edge_webhook_post to enqueue instead of net.http_post
CREATE OR REPLACE FUNCTION public._edge_webhook_post(
  p_function_name text,
  p_secret_name text,
  p_payload jsonb
) RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'pg_catalog, public'
AS $$
DECLARE
  v_secret text;
  v_id bigint;
BEGIN
  -- Validate secret existence at enqueue-time so triggers fail fast if misconfigured.
  v_secret := public._vault_secret(p_secret_name);

  IF v_secret IS NULL OR length(v_secret) < 10 THEN
    RAISE EXCEPTION 'Missing Vault secret % for edge webhook', p_secret_name;
  END IF;

  INSERT INTO public.edge_webhook_outbox(function_name, secret_name, payload, status, next_attempt_at)
  VALUES (p_function_name, p_secret_name, COALESCE(p_payload, '{}'::jsonb), 'pending', now())
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

ALTER FUNCTION public._edge_webhook_post(text, text, jsonb) OWNER TO postgres;

REVOKE ALL ON FUNCTION public._edge_webhook_post(text, text, jsonb) FROM PUBLIC;
GRANT ALL ON FUNCTION public._edge_webhook_post(text, text, jsonb) TO postgres;
GRANT ALL ON FUNCTION public._edge_webhook_post(text, text, jsonb) TO service_role;

-- 3) Service-role outbox worker RPCs
CREATE OR REPLACE FUNCTION public.edge_webhook_outbox_claim(
  p_limit integer DEFAULT 20,
  p_lock_id uuid DEFAULT gen_random_uuid()
) RETURNS TABLE(
  id bigint,
  function_name text,
  payload jsonb,
  secret_name text,
  secret text,
  attempts integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'pg_catalog, public'
AS $$
BEGIN
  IF auth.role() IS DISTINCT FROM 'service_role' THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  RETURN QUERY
  WITH due AS (
    SELECT o.id
    FROM public.edge_webhook_outbox o
    WHERE o.status IN ('pending','failed')
      AND o.next_attempt_at <= now()
    ORDER BY o.next_attempt_at ASC, o.id ASC
    LIMIT GREATEST(1, LEAST(COALESCE(p_limit, 20), 200))
    FOR UPDATE SKIP LOCKED
  )
  UPDATE public.edge_webhook_outbox o
  SET status = 'processing',
      lock_id = p_lock_id,
      locked_at = now(),
      attempts = o.attempts + 1
  FROM due
  WHERE o.id = due.id
  RETURNING
    o.id,
    o.function_name,
    o.payload,
    o.secret_name,
    public._vault_secret(o.secret_name) AS secret,
    o.attempts;
END;
$$;

ALTER FUNCTION public.edge_webhook_outbox_claim(integer, uuid) OWNER TO postgres;

REVOKE ALL ON FUNCTION public.edge_webhook_outbox_claim(integer, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.edge_webhook_outbox_claim(integer, uuid) FROM anon;
REVOKE ALL ON FUNCTION public.edge_webhook_outbox_claim(integer, uuid) FROM authenticated;
GRANT ALL ON FUNCTION public.edge_webhook_outbox_claim(integer, uuid) TO service_role;


CREATE OR REPLACE FUNCTION public.edge_webhook_outbox_mark(
  p_outbox_id bigint,
  p_lock_id uuid,
  p_status text,
  p_error text DEFAULT NULL,
  p_http_status integer DEFAULT NULL,
  p_retry_seconds integer DEFAULT NULL
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'pg_catalog, public'
AS $$
DECLARE
  v_retry interval;
BEGIN
  IF auth.role() IS DISTINCT FROM 'service_role' THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  IF p_status NOT IN ('sent','failed','pending') THEN
    RAISE EXCEPTION 'invalid_status';
  END IF;

  v_retry := make_interval(secs => GREATEST(1, LEAST(COALESCE(p_retry_seconds, 60), 3600)));

  UPDATE public.edge_webhook_outbox
  SET status = CASE WHEN p_status = 'pending' THEN 'pending' ELSE p_status END,
      last_error = p_error,
      last_http_status = p_http_status,
      last_dispatched_at = now(),
      next_attempt_at = CASE
        WHEN p_status = 'failed' THEN now() + v_retry
        WHEN p_status = 'pending' THEN now()
        ELSE next_attempt_at
      END,
      lock_id = NULL,
      locked_at = NULL
  WHERE id = p_outbox_id
    AND lock_id = p_lock_id;
END;
$$;

ALTER FUNCTION public.edge_webhook_outbox_mark(bigint, uuid, text, text, integer, integer) OWNER TO postgres;

REVOKE ALL ON FUNCTION public.edge_webhook_outbox_mark(bigint, uuid, text, text, integer, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.edge_webhook_outbox_mark(bigint, uuid, text, text, integer, integer) FROM anon;
REVOKE ALL ON FUNCTION public.edge_webhook_outbox_mark(bigint, uuid, text, text, integer, integer) FROM authenticated;
GRANT ALL ON FUNCTION public.edge_webhook_outbox_mark(bigint, uuid, text, text, integer, integer) TO service_role;


-- 4) Driver pickup PIN verification as a DB RPC (atomic + concurrency-safe)
CREATE OR REPLACE FUNCTION public.ride_verify_pickup_pin(
  p_ride_id uuid,
  p_pin text
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'pg_catalog, public, extensions'
AS $$
DECLARE
  v_uid uuid;
  r record;
  v_now timestamptz := now();
  v_fail int;
  v_locked_until timestamptz;
  v_secret text;
  v_mac bytea;
  b0 int; b1 int; b2 int; b3 int;
  n bigint;
  v_expected text;
BEGIN
  v_uid := auth.uid();
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;

  SELECT id, rider_id, driver_id, pickup_pin_required, pickup_pin_verified_at, pickup_pin_fail_count, pickup_pin_locked_until
  INTO r
  FROM public.rides
  WHERE id = p_ride_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'ride_not_found';
  END IF;

  IF r.driver_id IS DISTINCT FROM v_uid THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  IF NOT COALESCE(r.pickup_pin_required, false) THEN
    RETURN jsonb_build_object(
      'ok', true,
      'required', false,
      'verified', r.pickup_pin_verified_at IS NOT NULL,
      'verified_at', r.pickup_pin_verified_at
    );
  END IF;

  IF r.pickup_pin_verified_at IS NOT NULL THEN
    RETURN jsonb_build_object(
      'ok', true,
      'required', true,
      'verified', true,
      'verified_at', r.pickup_pin_verified_at
    );
  END IF;

  v_fail := COALESCE(r.pickup_pin_fail_count, 0);
  v_locked_until := r.pickup_pin_locked_until;

  IF v_locked_until IS NOT NULL AND v_locked_until > v_now THEN
    RETURN jsonb_build_object(
      'ok', false,
      'code', 'PIN_LOCKED',
      'fail_count', v_fail,
      'locked_until', v_locked_until
    );
  END IF;

  v_secret := public._vault_secret('PIN_SECRET');
  IF v_secret IS NULL OR length(v_secret) < 10 THEN
    RAISE EXCEPTION 'missing_pin_secret';
  END IF;

  v_mac := extensions.hmac(
    'ride_pin:' || r.id::text || ':' || r.rider_id::text || ':' || r.driver_id::text,
    v_secret,
    'sha256'
  );

  b0 := get_byte(v_mac, 0);
  b1 := get_byte(v_mac, 1);
  b2 := get_byte(v_mac, 2);
  b3 := get_byte(v_mac, 3);

  n := ((b0::bigint << 24) | (b1::bigint << 16) | (b2::bigint << 8) | b3::bigint);
  n := (n & 4294967295); -- force unsigned 32-bit

  v_expected := lpad(((n % 10000)::text), 4, '0');

  IF COALESCE(trim(p_pin), '') <> v_expected THEN
    v_fail := v_fail + 1;
    v_locked_until := CASE WHEN v_fail >= 5 THEN v_now + interval '10 minutes' ELSE NULL END;

    UPDATE public.rides
    SET pickup_pin_fail_count = v_fail,
        pickup_pin_last_attempt_at = v_now,
        pickup_pin_locked_until = v_locked_until
    WHERE id = p_ride_id;

    RETURN jsonb_build_object(
      'ok', false,
      'code', CASE WHEN v_locked_until IS NOT NULL THEN 'PIN_LOCKED' ELSE 'INVALID_PIN' END,
      'fail_count', v_fail,
      'remaining_attempts', GREATEST(0, 5 - v_fail),
      'locked_until', v_locked_until
    );
  END IF;

  UPDATE public.rides
  SET pickup_pin_verified_at = v_now,
      pickup_pin_fail_count = 0,
      pickup_pin_locked_until = NULL,
      pickup_pin_last_attempt_at = v_now
  WHERE id = p_ride_id;

  INSERT INTO public.ride_events(ride_id, actor_id, actor_type, event_type, payload)
  VALUES (
    p_ride_id,
    v_uid,
    'driver'::public.ride_actor_type,
    'pickup_pin_verified',
    jsonb_build_object('verified_at', v_now)
  );

  RETURN jsonb_build_object(
    'ok', true,
    'required', true,
    'verified', true,
    'verified_at', v_now
  );
END;
$$;

ALTER FUNCTION public.ride_verify_pickup_pin(uuid, text) OWNER TO postgres;

REVOKE ALL ON FUNCTION public.ride_verify_pickup_pin(uuid, text) FROM PUBLIC;
GRANT ALL ON FUNCTION public.ride_verify_pickup_pin(uuid, text) TO service_role;
GRANT ALL ON FUNCTION public.ride_verify_pickup_pin(uuid, text) TO authenticated;
