-- Ensure provider event log table exists (used by payment/topup edge functions for debugging & idempotency)

create table if not exists public.provider_events (
  id bigint generated by default as identity primary key,
  provider_code text not null,
  provider_event_id text not null,
  payload jsonb not null default '{}'::jsonb,
  received_at timestamp with time zone not null default now(),
  constraint provider_events_provider_code_fkey
    foreign key (provider_code)
    references public.payment_providers(code)
    on delete cascade
);

-- Each provider emits unique event ids, so de-duplicate per provider.
create unique index if not exists provider_events_provider_code_provider_event_id_key
  on public.provider_events(provider_code, provider_event_id);

create index if not exists provider_events_provider_code_received_at_idx
  on public.provider_events(provider_code, received_at desc);
